name: documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.11"
          enablle-cache: true
          cache-dependency-glob: uv.lock
      - name: Install dependencies
        run: uv sync --locked --all-extras
      - name: Generate documentation
        run: uv run sphinx-build docs _build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{github.ref == 'refs/heads/main' && github.event_name == 'push'}}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build
          force_orphan: true
