name: release

on:
  release:
    types:
      - published

jobs:
  build:
    name: build and publish to PyPI
    environment: pypi
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.11"
          enable-cache: true
          cache-dependency-glob: uv.lock
      - name: Install build dependencies
        run: uv sync --locked --all-extras
      - name: Build package distributions
        run: uv build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
